import Link from 'next/link';
import { LandingHeader } from '@/components/LandingHeader';
import { LandingFooter } from '@/components/LandingFooter';

export default function PrivacyPage() {
  return (
    <div className="landing-container">
      <LandingHeader />
      <main className="landing-main mx-auto max-w-2xl px-6 py-16 text-[#F2F5F3]">
        <h1 className="font-display text-4xl font-bold italic">Privacy policy</h1>
        <p className="mt-2 text-sm text-[#9AABA0]">Last updated 3 September 2026</p>
        <div className="mt-8 space-y-4 text-sm leading-relaxed text-[#D5DDD8]">
          <p>
            Harmonix is a language-learning app that uses real song lyrics. This
            page describes what we store when you use the website or the Android
            app at{' '}
            <Link href="https://harmonix.peeporunclub.co.uk" className="underline">
              harmonix.peeporunclub.co.uk
            </Link>
            .
          </p>
          <h2 className="pt-4 text-lg font-semibold text-white">Account data</h2>
          <p>
            If you create an account we store your email, a hashed password,
            language and music-style preferences, and learning progress (word
            queue, reviews, playlists, badges). We do not store your password in
            plain text.
          </p>
          <h2 className="pt-4 text-lg font-semibold text-white">Music and Spotify</h2>
          <p>
            Song search and 30-second previews come from Deezer and LRCLib.
            If you connect Spotify we store encrypted OAuth tokens and playlist
            metadata so you can export Harmonix playlists and, on the web, play
            clips when you have Spotify Premium. We do not host full songs.
          </p>
          <h2 className="pt-4 text-lg font-semibold text-white">Pronunciation audio</h2>
          <p>
            Spoken words are generated by a text-to-speech service on our
            servers and may be cached so the same word does not need to be
            synthesized again.
          </p>
          <h2 className="pt-4 text-lg font-semibold text-white">Contact</h2>
          <p>
            Questions: info@harmonix.app. To delete an account, email that
            address from the address on the account.
          </p>
        </div>
      </main>
      <LandingFooter />
    </div>
  );
}
